<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260227163154 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE deployment_confirmation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, confirmed_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT NULL, deployment_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D2D3128D70AD6533 ON deployment_confirmation (deployment_user_id)');
        $this->addSql('CREATE TABLE deployment_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(7) NOT NULL, deployment_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_21BAB28E9DF4CE98 ON deployment_user (deployment_id)');
        $this->addSql('CREATE INDEX IDX_21BAB28EA76ED395 ON deployment_user (user_id)');
        $this->addSql('ALTER TABLE deployment_confirmation ADD CONSTRAINT FK_D2D3128D70AD6533 FOREIGN KEY (deployment_user_id) REFERENCES deployment_user (id)');
        $this->addSql('ALTER TABLE deployment_user ADD CONSTRAINT FK_21BAB28E9DF4CE98 FOREIGN KEY (deployment_id) REFERENCES queued_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deployment_user ADD CONSTRAINT FK_21BAB28EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deployment_notify_user DROP CONSTRAINT fk_a84e097e9df4ce98');
        $this->addSql('ALTER TABLE deployment_notify_user DROP CONSTRAINT fk_a84e097ea76ed395');
        $this->addSql("INSERT INTO deployment_user (type, deployment_id, user_id) SELECT 'notify' as type, deployment_id, user_id from deployment_notify_user");
        $this->addSql('DROP TABLE deployment_notify_user');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_58DF0651A76ED39582D40A1F ON administrator (user_id, workspace_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE deployment_notify_user (deployment_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (deployment_id, user_id))');
        $this->addSql('CREATE INDEX idx_a84e097ea76ed395 ON deployment_notify_user (user_id)');
        $this->addSql('CREATE INDEX idx_a84e097e9df4ce98 ON deployment_notify_user (deployment_id)');
        $this->addSql('ALTER TABLE deployment_notify_user ADD CONSTRAINT fk_a84e097e9df4ce98 FOREIGN KEY (deployment_id) REFERENCES queued_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deployment_notify_user ADD CONSTRAINT fk_a84e097ea76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deployment_confirmation DROP CONSTRAINT FK_D2D3128D70AD6533');
        $this->addSql('ALTER TABLE deployment_user DROP CONSTRAINT FK_21BAB28E9DF4CE98');
        $this->addSql('ALTER TABLE deployment_user DROP CONSTRAINT FK_21BAB28EA76ED395');
        $this->addSql('insert into deployment_notify_user (deployment_id, user_id) select deployment_id, user_id from deployment_user');
        $this->addSql('DROP TABLE deployment_confirmation');
        $this->addSql('DROP TABLE deployment_user');
        $this->addSql('DROP INDEX UNIQ_58DF0651A76ED39582D40A1F');
    }
}
